// frontend/solid-js/src/App.tsx
import { createSignal } from "solid-js";
import { Counter, Header } from "~/components";

function App() {
  return (
    <main>
      <Header />
      <section class="container mx-auto flex items-center justify-center mt-8">
        <Counter />
      </section>
    </main>
  );
}

export default App;

// frontend/preact-js/src/app.tsx
import "preact/devtools";
import { Outlet, ScrollRestoration } from "react-router-dom";

import { Header } from "~/components";

export default function App() {
  return (
    <section className="container mx-auto">
      <Header />
      <main>
        <Outlet />
      </main>
      <ScrollRestoration />
    </section>
  );
}
