// frontend/preact-js/src/app/Issues/components/IssueList.tsx
import { IssueItem } from "~/app/Issues/components";

export const IssueList = () => {
  return (
    <div className="card border-white">
      <div className="card-header bg-dark">
        <ul className="nav nav-pills card-header-pills">
          <li className="nav-item">
            <a className="nav-link active">All</a>
          </li>
          <li className="nav-item">
            <a className="nav-link">Open</a>
          </li>
          <li className="nav-item">
            <a className="nav-link">Closed</a>
          </li>
        </ul>
      </div>
      <div className="card-body text-dark">
        {[1, 2, 3].map((issue) => (
          <IssueItem key={issue} />
        ))}
      </div>
    </div>
  );
};

// frontend/solid-js/src/app/Issues/components/IssueList.tsx
import { For } from "solid-js";
import { IssueItem } from "~/app/Issues/components";

export const IssueList = () => {
  return (
    <div class="card border-white">
      <div class="card-header bg-dark">
        <ul class="nav nav-pills card-header-pills">
          <li class="nav-item">
            <a class="nav-link active">All</a>
          </li>
          <li class="nav-item">
            <a class="nav-link">Open</a>
          </li>
          <li class="nav-item">
            <a class="nav-link">Closed</a>
          </li>
        </ul>
      </div>
      <div class="card-body text-dark">
        <For each={[1, 2, 3]}>{() => <IssueItem />}</For>
      </div>
    </div>
  );
};
